#!/usr/bin/perl

$integer = 200;
$negative = -300;
$floating = 240.56;
$bigfloat = -1.2E-23;

$octal = 0377;

$hexa = 0xff;

print "integer = $integer\n";
print "negative = $negative\n";
print "floating = $foating\n";
print "bigfloat = $bigfloat\n";
print "octal = $octal\n";
print "hexa = $hexa\n";
