#!/usr/bin/perl

$var = "This is a string scalar";
$quote = 'This is inside a single quote - $var';
$double = "This is inside double quote - $var";

$escape = "This is example of escape - \tHello World";

print "var = $var\n";
print "quote = $quote\n";
print "double = $double\n";
print "escape = $escape\n";
